### ISSUE TITLE
Build Mock-Up

### ISSUE THREAD

**Issue by Globnartheexquisite** [saucelabs/elemental-next#57]
Carried over from #28 

# Description

Build the first iteration of the figma mock-ups. Content to be changed BUT content present in the mock-up. UI to be evolved, but present in the mock up 

# Criteria

- [x] Information Architecture workshopped and mapped
- [x] Tip List Page #8 
- [x] Individual Tip page #64 
- [x] Colors selected
- [x] Text updated
- [x] Components laid out
- [x] Landing Page #9 
- [x] Community Page #225 
- [x] External Resources page #224 
- [x] Talk to Marija about illustrative graphics available from Sauce(?)
- [x] All buttons/interactive components are at least prototyped for five states

**Comment by Globnartheexquisite** [comment]
Site mockup created, draft one reviewed, draft two completed and submitted for review.
